In [37]:
import numpy as np

In [38]:
arr=np.array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [39]:
arr.ndim 
arr.shape

(5,)

In [40]:
arr2=np.array([[12,33,44],[3,2,6]])


In [41]:
arr2.ndim


2

In [42]:
arr[1:4]

array([2, 3, 4])

In [43]:
np.mean(arr2,axis=1)

array([29.66666667,  3.66666667])

In [44]:
np.array(arr+5)

array([ 6,  7,  8,  9, 10])

In [45]:
np.array(arr/5)


array([0.2, 0.4, 0.6, 0.8, 1. ])

In [46]:
np.array(arr<3)

array([ True,  True, False, False, False])

In [47]:
np.dot(arr,3)

array([ 3,  6,  9, 12, 15])